export const pageElements = {
  singinPageElements: {
    signinBtn: "signin-button",
    signupLink: "signup-link",
    emailInput: "email-input",
    emailErr: "email-error",
    passInput: "password-input",
    passErr: "password-error",
    persistLoginCheck: "persist-login-check",
  },
  signupPageElements: {
    signupBtn: "signup-button",
    signinLink: "signin-link",
    firstNameErr: "first-name-error",
    emailErr: "email-error",
    passErr: "password-error",
    confirmPassErr: "confirm-password-error",
    firstNameInput: "first-name-input",
    emailInput: "email-input",
    passInput: "password-input",
    confirmPassInput: "confirm-password-input",
  },
  homePageElements: {
    siteLogo: "site-logo",
    userAvatar: "user-avatar",
    createAccount: "create_account",
    createPostBtn: "create-post-btn",
    bookmark: "bookmark",
    nonBookmarkedArticles: "article[data-bookmark='false']",
    bookmarkedArticles: "article[data-bookmark='true']",
    deskTopMenuItems: {
      userProfileLink: "user-profile-link",
      homeLink: "home-link",
      dashboardLink: "dashboard-link",
      createPostLink: "create-post-link",
      editProfileLink: "edit-profile-link",
      bookmarkLink: "bookmark-link",
      followersLink: "followers-link",
      followingUsersLink: "following-users-link",
      logoutLink: "logout-link",
    },
    discoverPostsPageBtn: "discover-posts-page-btn",
    followingPostsPageBtn: "following-posts-page-btn",
    discoverPostsPage: "discover-posts-page",
    followingPostsPage: "following-posts-page",
    topLikedArticlesCnt:"top-liked-articles-container",
    topDiscussedArticlesCnt:"top-discussed-articles-container",
  },
  followersPageElements: {
    followersHeader: "followers-header",
    followersNotFound: "followers-not-found",
    customSelectFollowerTrigger:"custom-select-trigger-follower"
  },
  followingUsersPageElements: {
    followingUsersHeader: "following-users-header",
    followingsNotFound: "followings-not-found",
  },
  followedAt:"followed-at",
  editCommentPageElements: {
    editCommentHeader: "edit-comment-header",
    editCmtSubmitBtn: "edit-comment-submit-btn",
    editCmtDismissBtn: "edit-comment-dismiss-btn",
    editCmtTxtArea: "edit-comment-text-area",
  },
  deleteCommentPageElements: {
    deleteCommentModal: "delete-comment-modal",
    deleteCommentBtn: "delete-comment-btn",
    cancelDeleteCommentBtn: "cancel-delete-comment-btn",
  },
  deletePostPageElements: {
    deletePostModal: "delete-post-modal",
    deletePostSubmitBtn: "delete-post-submit-btn",
  },
  modal: {
    requireLoginModal: "require-login-modal",
    closeModal: "close-modal",
  },
  individualPostPageElements: {
    bookmark: "bookmark",
    like: "like",
    comment: "comment",
    totalComments: "total-comments",
    createCmtTxtArea: "create-comment-text-area",
    replyCmtTxtArea: "reply-comment-text-area",
    createCmtSubmitBtn: "create-comment-submit-btn",
    replyCmtSubmitBtn: "reply-comment-submit-btn",
    commentFooter: "comment-footer",
    replyCmtBtn: "reply-comment-btn",
    replyCmtDismissBtn: "reply-comment-dismiss-btn",
    commentsList: "comments-list",
    commentListComment: "comment-list-comment",
    commentContent: "comment-content",
    commentMenuTrigger: "comment-menu-trigger",
    likeCommentBtn: "like-comment-btn",
    userInfoCardHeader: "user-info-card-header",
    deleteCmtMenuBtn: "delete-cmt-button",
    editCmtMenuBtn: "edit-cmt-button",
    individualPostContainer: "individual-post-container",
    individualPostPageSkeleton: "individual-post-page-skeleton",
    commentSkeleton: "comment-skeleton",
    editUserBtn:"edit-user-btn"
  },
  userProfilePageElements: {
    userName: "user-profile-user-name",
  },
  dashBoardPageElements: {
    dashboardHeaderTitle: "dashboard-header-title",
    dashboardTotalPostLikes: "dashboard-total-likes",
    dashboardTotalPosts: "dashboard-total-posts",
    dashboardTotalPostComments: "dashboard-total-comments",
    deletePostBtn: "delete-post-button",
    editPostBtn: "edit-post-button",
  },
  createPostPageElements: {
    showPreviewBtn: "show-preview-btn",
    createPostSubmitBtn: "create-post-submit-btn",
    postTitleTxtArea: "post-title-text-area",
    postContentTxtArea: "post-content-text-area",
    hashtagLink: "hashtag-link",
    hashtagInput: "hashtag-input",
    hashtagError: "hashtag-error",
    hashtagList: "hashtag-list",
    hashtagWarning: "hashtag-warning",
    removeHashtagBtn: "remove-hashtag-btn",
    editPostBtn: "edit-post-btn",
    backBtn: "back-btn",
  },
  editUserProfilePageElements: {
    editUserProfileHeader: "edit-user-profile-header",
  },
  bookmarkPageElements: {
    bookmarkHeader: "bookmark-header",
    bookmarkedAtDate:"bookmarked-at-date",
    customSelectBookmarkTrigger:"custom-select-trigger-bookmark",
  },
  taggedPostPageElements:{
    taggedPostHeader:"tagged-post-header"
  },

  TerminateSessionPageElements: {
    terminateEmailInput: "terminate-email-input",
    terminatePassInput: "terminate-password-input",
    terminateSessionBtn: "terminate-session-btn",
  },
  postArticle: {
    article: "post-article",
    bookmark: "bookmark",
    title: "post-title",
    articlesSkeleton: "articles-skeleton",
  },
  followButton: "follow-button",
  toastMsg: {
    error: {
      wrongPassMsg: "Invalid password !",
      createPostErr: {
        titleContentErrMsg: "Please add title and content to create post.",
        showPreviewPostErrMsg: "Please add title and content to preview.",
        maxPostTitleLenErrMsg: "Post title length cannot exceed 60 characters.",
      },
    },
    success: {
      editCmtSuccessMsg: "comment edited successfully !!",
    },
  },
  loadingSpinner: "loading-spinner",
   hashtagListElement: "hashtag-list-element",
   searchPostInput:"search-post-input",
  searchSuggestionsSkeleton :"search-suggestions-skeleton",
  searchSuggestionItem:"search-suggestions-item",
  searchPostBtn:"search-post-btn",
  noSearchPostFound:"no-searched-post-found",
  searPostPageElements:{
    searchPostHeader:"search-post-header"
  },
  tagFilterTrigger:"tag-filter-trigger",
  tagListElement:"tag-list-element",
  selectItemASC:"select-item-asc",
  selectItemDESC:"select-item-desc",
};

export const paths = {
  home: "/",
  userProfilePage: "/userprofile",
  dashboardPage: "/dashboard",

  createPostPage: "/new",
  editUserProfilePage: "/update/user",
  bookmarkPage: "/bookmark",
  signinPage: "/signin",
  signupPage: "/signup",
  individualPostPage: "/post",
  terminate: "/terminate",
  followersPage: "/followers",
  followingUsersPage: "/followings",
  editCommentPage: "/comment/edit",
  deleteCommentPage: "/comment/delete",
  deletePostPage: "/post/delete",
  createCommentPath: "/comment",
  getUserPostsPath: "/user/posts",
  getUserStatsPath: "/user/stat",
  taggedPostPath:"/tag",
  searchPostPath:"/search"
};
